version: '3.8'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/var/www/html:ro
    depends_on:
      - php-fpm

  php-fpm:
    image: php:8.3-fpm-alpine
    container_name: php-fpm
    restart: unless-stopped
    volumes:
      - ./public:/var/www/html:ro
      - ./php/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
    environment:
      - DB_HOST=mariadb
      - DB_NAME=cmpe-272
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    command: >
      sh -c "docker-php-ext-install pdo_mysql && php-fpm"

  mariadb:
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=cmpe-272
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    command: --innodb-buffer-pool-size=128M
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", -u", "${DB_USER}", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
