version: '3.8'

services:
  mariadb:
    extends:
      file: docker-compose-base.yml
      service: mariadb

  nginx:
    extends:
      file: docker-compose-base.yml
      service: nginx-base
    build:
      context: .
      dockerfile: nginx/Dockerfile
      target: development
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/var/www/html/public:ro

  php-fpm:
    extends:
      file: docker-compose-base.yml
      service: php-fpm-base
    build:
      context: .
      dockerfile: php/Dockerfile
      target: development
    volumes:
      - ./:/var/www/html
      - ./php/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro

volumes:
  db_data:
